version: 2
registries:
  ghcr:
    type: docker-registry
    url: https://ghcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}
    replaces-base: true
updates:
  - package-ecosystem: "docker"
    directory: "foo"
    registries: "*"
    schedule:
      interval: "daily"
